name: Deploying the my. portfolio website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: us-east-1
    
    -  name: Install terraform
       uses: hashicorp/setup-terraform@v3.1.2
       with:
         terraform_version: 1.12.2

    - name: terraform init
      run: terraform init
      working-directory: ./terraform/portfolio-infra/

    - name: terraform plan
      run: terraform plan
      working-directory: ./terraform/portfolio-infra/

    - name: terraform apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/portfolio-infra/


  node_setup:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.19.0'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
    
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: us-east-1
    
    - name: sync files to s3
      run: |
        aws s3 sync dist s3://portfolio-nithish --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }} --paths "/*"